#!/bin/bash

add-apt-repository ppa:neovim-ppa/stable
apt-get install upgrade
apt-get install install neovim

cd $HOME && git clone https://github.com/Existentialdredd/vimrc.git

mv vimrc dot_files

cd dot_files && git checkout personal_docker

./symlinks/links

nvim --headless +PlugInstall +qa
nvim --headless +Plugall +qa
